### ISSUE TITLE
17.1 compiles without error, but hangs at boot animation

### ISSUE THREAD

**Issue by retiredtab** [Galaxy-MSM8916/android_device_samsung_gtelwifiue#2]
Has anyone successfully gotten 17.1 to load on gtelwifiue (SM-T560NU) or gt58wifi (SM-T350)?

I can get 17.1 to compile without error, but hangs at boot animation.  I cannot get a log file when it hangs because adb doesn't respond.

I'm able to get 16.0 working on both tablets above, but something changed in 17.1?

**Comment by retiredtab** [comment]
For anyone finding this, it gets stuck at boot animation because of the hal vibrator.  Remove it from the device/samsung/msm8916-common/manifest.xml and code runs and works.

**Comment by BAProductions** [comment]
17.1 has been compiled

**Comment by BAProductions** [comment]
> For anyone finding this, it gets stuck at boot animation because of the hal vibrator. Remove it from the device/samsung/msm8916-common/manifest.xml and code runs and works.

I have!!!!
